version: "3.8"
services:
  api:
    build: ./express
    ports:
      - '80:80'
    volumes:
      - ./express:/app # bind mount to auto updates
      - /app/node_modules # does not use our host node_modules